
import java.util.List;
import java.sql.Date;
import javax.swing.DefaultComboBoxModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MauriLitvak
 */
public class GUIFrame extends javax.swing.JFrame {
    
    //Customer
    Customer customer = new Customer();
    List< String > customerList = customer.getAllCustomers();
    
    //Flight
    Flight flight = new Flight();
    List< String > flightList = flight.getAllFlights();
    //Day
    Day day = new Day();
    List< String > dateList = day.getAllDays();
    /**
     * Creates new form GUIFrame
     */
    public GUIFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitlejLabel = new javax.swing.JLabel();
        jTabbedPane = new javax.swing.JTabbedPane();
        AddCustomerjPanel = new javax.swing.JPanel();
        CustomerNamejLabel = new javax.swing.JLabel();
        CustomerNamejTextField = new javax.swing.JTextField();
        AddCustomerjButton = new javax.swing.JButton();
        AddCustomerjTextField = new javax.swing.JTextField();
        BookingjPanel = new javax.swing.JPanel();
        FlightjComboBox = new javax.swing.JComboBox<>();
        DatejComboBox = new javax.swing.JComboBox<>();
        CustomerjComboBox = new javax.swing.JComboBox<>();
        BookFlightjButton = new javax.swing.JButton();
        BookingStatusjTextField = new javax.swing.JTextField();
        FlightStatusjPanel = new javax.swing.JPanel();
        FlightjComboBox1 = new javax.swing.JComboBox<>();
        DatejComboBox1 = new javax.swing.JComboBox<>();
        FlightStatusjButton = new javax.swing.JButton();
        FlightStatusjTextField = new javax.swing.JTextField();
        WaitlistStatusjPanel = new javax.swing.JPanel();
        DatejComboBox2 = new javax.swing.JComboBox<>();
        WaitlistStatusjButton = new javax.swing.JButton();
        WaitlistStatusjTextField = new javax.swing.JTextField();
        SignaturejLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        TitlejLabel.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        TitlejLabel.setForeground(new java.awt.Color(255, 51, 51));
        TitlejLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        TitlejLabel.setText("Flight Scheduler");
        TitlejLabel.setAlignmentX(0.5F);
        TitlejLabel.setAlignmentY(0.0F);

        jTabbedPane.setBackground(new java.awt.Color(240, 240, 240));

        CustomerNamejLabel.setText("Customer Name:");

        CustomerNamejTextField.setColumns(20);
        CustomerNamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerNamejTextFieldActionPerformed(evt);
            }
        });

        AddCustomerjButton.setText("Add");
        AddCustomerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCustomerjButtonActionPerformed(evt);
            }
        });

        AddCustomerjTextField.setEditable(false);
        AddCustomerjTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AddCustomerjTextField.setText("Add Customer Status Indicator");
        AddCustomerjTextField.setToolTipText("Displays if Customer was added to database succesfully");
        AddCustomerjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCustomerjTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddCustomerjPanelLayout = new javax.swing.GroupLayout(AddCustomerjPanel);
        AddCustomerjPanel.setLayout(AddCustomerjPanelLayout);
        AddCustomerjPanelLayout.setHorizontalGroup(
            AddCustomerjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddCustomerjPanelLayout.createSequentialGroup()
                .addGroup(AddCustomerjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddCustomerjPanelLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(AddCustomerjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddCustomerjPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CustomerNamejLabel)
                        .addGap(18, 18, 18)
                        .addComponent(CustomerNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
            .addComponent(AddCustomerjTextField)
        );
        AddCustomerjPanelLayout.setVerticalGroup(
            AddCustomerjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddCustomerjPanelLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(AddCustomerjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerNamejLabel)
                    .addComponent(CustomerNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(AddCustomerjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(AddCustomerjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Add Customer", AddCustomerjPanel);

        FlightjComboBox.setModel(new DefaultComboBoxModel(flightList.toArray()));
        FlightjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightjComboBoxActionPerformed(evt);
            }
        });

        DatejComboBox.setModel(new DefaultComboBoxModel(dateList.toArray()));
        DatejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatejComboBoxActionPerformed(evt);
            }
        });

        CustomerjComboBox.setModel(new DefaultComboBoxModel(customerList.toArray()));
        CustomerjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerjComboBoxActionPerformed(evt);
            }
        });

        BookFlightjButton.setText("Book Flight");
        BookFlightjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookFlightjButtonActionPerformed(evt);
            }
        });

        BookingStatusjTextField.setEditable(false);
        BookingStatusjTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BookingStatusjTextField.setText("Booking Status Indicator");

        javax.swing.GroupLayout BookingjPanelLayout = new javax.swing.GroupLayout(BookingjPanel);
        BookingjPanel.setLayout(BookingjPanelLayout);
        BookingjPanelLayout.setHorizontalGroup(
            BookingjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingjPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FlightjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BookingjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookingjPanelLayout.createSequentialGroup()
                        .addComponent(DatejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CustomerjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(BookingjPanelLayout.createSequentialGroup()
                        .addComponent(BookFlightjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(BookingjPanelLayout.createSequentialGroup()
                .addComponent(BookingStatusjTextField)
                .addContainerGap())
        );
        BookingjPanelLayout.setVerticalGroup(
            BookingjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingjPanelLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(BookingjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FlightjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DatejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustomerjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BookFlightjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(BookingStatusjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jTabbedPane.addTab("Booking", BookingjPanel);

        FlightjComboBox1.setModel(new DefaultComboBoxModel(flightList.toArray()));
        FlightjComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightjComboBox1ActionPerformed(evt);
            }
        });

        DatejComboBox1.setModel(new DefaultComboBoxModel(dateList.toArray()));
        DatejComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatejComboBox1ActionPerformed(evt);
            }
        });

        FlightStatusjButton.setText("Check Status");
        FlightStatusjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightStatusjButtonActionPerformed(evt);
            }
        });

        FlightStatusjTextField.setEditable(false);
        FlightStatusjTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FlightStatusjTextField.setText("Displays Status by Flight and Day");
        FlightStatusjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightStatusjTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FlightStatusjPanelLayout = new javax.swing.GroupLayout(FlightStatusjPanel);
        FlightStatusjPanel.setLayout(FlightStatusjPanelLayout);
        FlightStatusjPanelLayout.setHorizontalGroup(
            FlightStatusjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FlightStatusjPanelLayout.createSequentialGroup()
                .addGroup(FlightStatusjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FlightStatusjPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(FlightjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(DatejComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FlightStatusjPanelLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(FlightStatusjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(FlightStatusjTextField)
        );
        FlightStatusjPanelLayout.setVerticalGroup(
            FlightStatusjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FlightStatusjPanelLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(FlightStatusjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DatejComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FlightjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(FlightStatusjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FlightStatusjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane.addTab("Flight Status", FlightStatusjPanel);

        DatejComboBox2.setModel(new DefaultComboBoxModel(dateList.toArray()));
        DatejComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatejComboBox2ActionPerformed(evt);
            }
        });

        WaitlistStatusjButton.setText("Check Waitlist");
        WaitlistStatusjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WaitlistStatusjButtonActionPerformed(evt);
            }
        });

        WaitlistStatusjTextField.setEditable(false);
        WaitlistStatusjTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        WaitlistStatusjTextField.setText("Displays Waitlist Status by Date");

        javax.swing.GroupLayout WaitlistStatusjPanelLayout = new javax.swing.GroupLayout(WaitlistStatusjPanel);
        WaitlistStatusjPanel.setLayout(WaitlistStatusjPanelLayout);
        WaitlistStatusjPanelLayout.setHorizontalGroup(
            WaitlistStatusjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WaitlistStatusjPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(DatejComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(WaitlistStatusjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
            .addComponent(WaitlistStatusjTextField, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        WaitlistStatusjPanelLayout.setVerticalGroup(
            WaitlistStatusjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WaitlistStatusjPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(WaitlistStatusjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DatejComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WaitlistStatusjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(WaitlistStatusjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Waitlist Status", WaitlistStatusjPanel);

        SignaturejLabel.setFont(new java.awt.Font("Lucida Grande", 0, 8)); // NOI18N
        SignaturejLabel.setText("Mauricio I. Litvak");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitlejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SignaturejLabel))
            .addComponent(jTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TitlejLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SignaturejLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BookFlightjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookFlightjButtonActionPerformed
       BookingQueries booking = new BookingQueries();
       String CUSTOMER = (String) CustomerjComboBox.getSelectedItem();
       String FLIGHT = (String) FlightjComboBox.getSelectedItem();
       Date DATE = Date.valueOf(DatejComboBox.getSelectedItem().toString()); 
       booking.addBooking(CUSTOMER, FLIGHT, DATE);
       String customerBooked = CUSTOMER + " is booked for flight " + FLIGHT + " on " + DATE;
       String customerWaitlisted = "'"+ CUSTOMER + "'" + " is waitlisted for flight " + FLIGHT + " on " + DATE;
       if (booking.getBookingStatus())
       {
           BookingStatusjTextField.setText(customerBooked);
       }
       else if (booking.getWaitlistStatus())
       {
           BookingStatusjTextField.setText(customerWaitlisted);
       }
    }//GEN-LAST:event_BookFlightjButtonActionPerformed

    private void CustomerjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerjComboBoxActionPerformed
    String CUSTOMER = (String) CustomerjComboBox.getSelectedItem();
    System.out.println(CUSTOMER);
    }//GEN-LAST:event_CustomerjComboBoxActionPerformed

    private void DatejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatejComboBoxActionPerformed
    String DATE = (String) DatejComboBox.getSelectedItem();
    System.out.println(DATE);
    }//GEN-LAST:event_DatejComboBoxActionPerformed

    private void FlightjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightjComboBoxActionPerformed
    String FLIGHT = (String) FlightjComboBox.getSelectedItem();
    System.out.println(FLIGHT);
    }//GEN-LAST:event_FlightjComboBoxActionPerformed

    private void AddCustomerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCustomerjButtonActionPerformed
        customer.addCustomer(CustomerNamejTextField.getText());
        CustomerjComboBox.addItem(CustomerNamejTextField.getText());
        String added = "'" + CustomerNamejTextField.getText() + "'" + " was added to the Database";
        if (customer.getCustomerAddStatus())
        {
            AddCustomerjTextField.setText(added);
        }
        else
        {
            AddCustomerjTextField.setText("Customer NOT added to Database");
        }
    }//GEN-LAST:event_AddCustomerjButtonActionPerformed

    private void CustomerNamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerNamejTextFieldActionPerformed
        CustomerNamejTextField.getText();
    }//GEN-LAST:event_CustomerNamejTextFieldActionPerformed

    private void FlightjComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightjComboBox1ActionPerformed
    String FLIGHT = (String) FlightjComboBox1.getSelectedItem();
    System.out.println(FLIGHT);
    }//GEN-LAST:event_FlightjComboBox1ActionPerformed

    private void DatejComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatejComboBox1ActionPerformed
    Date DATE = Date.valueOf(DatejComboBox1.getSelectedItem().toString()); 
    System.out.println(DATE);
    }//GEN-LAST:event_DatejComboBox1ActionPerformed

    private void DatejComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatejComboBox2ActionPerformed
    Date DATE = Date.valueOf(DatejComboBox2.getSelectedItem().toString()); 
    System.out.print(DATE);
    }//GEN-LAST:event_DatejComboBox2ActionPerformed

    private void FlightStatusjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightStatusjButtonActionPerformed
    BookingQueries booking = new BookingQueries();
    String FLIGHT = (String) FlightjComboBox1.getSelectedItem();
    Date DATE = Date.valueOf(DatejComboBox1.getSelectedItem().toString()); 
    booking.getStatusByFlightDay(FLIGHT, DATE);
    System.out.print(booking.getStatusByFlightDay(FLIGHT, DATE));
    String bookingStatusList = String.join(", ", booking.getStatusByFlightDay(FLIGHT, DATE));
    String bookingStatus = "Customer(s) " + bookingStatusList + " are booked for " + FLIGHT + " on " + DATE;
    FlightStatusjTextField.setText(bookingStatus);
    }//GEN-LAST:event_FlightStatusjButtonActionPerformed

    private void WaitlistStatusjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WaitlistStatusjButtonActionPerformed
    Waitlist waitlist = new Waitlist();
    Date DATE = Date.valueOf(DatejComboBox2.getSelectedItem().toString()); 
    waitlist.getStatusByDay(DATE);
    String waitlistStatusList = String.join(", ", waitlist.getStatusByDay(DATE));
    WaitlistStatusjTextField.setText(waitlistStatusList);
    }//GEN-LAST:event_WaitlistStatusjButtonActionPerformed

    private void AddCustomerjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCustomerjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddCustomerjTextFieldActionPerformed

    private void FlightStatusjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightStatusjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FlightStatusjTextFieldActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCustomerjButton;
    private javax.swing.JPanel AddCustomerjPanel;
    private javax.swing.JTextField AddCustomerjTextField;
    private javax.swing.JButton BookFlightjButton;
    private javax.swing.JTextField BookingStatusjTextField;
    private javax.swing.JPanel BookingjPanel;
    private javax.swing.JLabel CustomerNamejLabel;
    private javax.swing.JTextField CustomerNamejTextField;
    private javax.swing.JComboBox<String> CustomerjComboBox;
    private javax.swing.JComboBox<String> DatejComboBox;
    private javax.swing.JComboBox<String> DatejComboBox1;
    private javax.swing.JComboBox<String> DatejComboBox2;
    private javax.swing.JButton FlightStatusjButton;
    private javax.swing.JPanel FlightStatusjPanel;
    private javax.swing.JTextField FlightStatusjTextField;
    private javax.swing.JComboBox<String> FlightjComboBox;
    private javax.swing.JComboBox<String> FlightjComboBox1;
    private javax.swing.JLabel SignaturejLabel;
    private javax.swing.JLabel TitlejLabel;
    private javax.swing.JButton WaitlistStatusjButton;
    private javax.swing.JPanel WaitlistStatusjPanel;
    private javax.swing.JTextField WaitlistStatusjTextField;
    private javax.swing.JTabbedPane jTabbedPane;
    // End of variables declaration//GEN-END:variables
}
