
import java.util.List;
import java.sql.Date;
import javax.swing.DefaultComboBoxModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MauriLitvak
 */
public class GUIFrame extends javax.swing.JFrame {
    
    //Customer
    Customer customer = new Customer();
    List< String > customerList = customer.getAllCustomers();
    
    //Flight
    Flight flight = new Flight();
    List< String > flightList = flight.getAllFlights();
    //Day
    Day day = new Day();
    List< String > dateList = day.getAllDays();
    
    BookingQueries booking = new BookingQueries();
    /**
     * Creates new form GUIFrame
     */
    public GUIFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        CompanyNamejLabel = new javax.swing.JLabel();
        TitlejLabel = new javax.swing.JLabel();
        SignaturejLabel = new javax.swing.JLabel();
        DropFlightjTabbedPane = new javax.swing.JTabbedPane();
        ManagejPanel = new javax.swing.JPanel();
        CustomerNamejLabel = new javax.swing.JLabel();
        CustomerNamejTextField = new javax.swing.JTextField();
        AddCustomerjButton = new javax.swing.JButton();
        AddCustomerjTextField = new javax.swing.JTextField();
        AddFlightNamejTextField = new javax.swing.JTextField();
        AddFlightNamejLabel = new javax.swing.JLabel();
        AddFlightSeatsjTextField = new javax.swing.JTextField();
        AddFlightSeatsjLabel = new javax.swing.JLabel();
        AddFlightjButton = new javax.swing.JButton();
        AddFlightStatusjTextField = new javax.swing.JTextField();
        AddDateMonthjTextField = new javax.swing.JTextField();
        AddCustomerjLabel = new javax.swing.JLabel();
        AddFlightjLabel = new javax.swing.JLabel();
        AddDatejLabel = new javax.swing.JLabel();
        AddDateMonthjLabel = new javax.swing.JLabel();
        AddDateDayjTextField = new javax.swing.JTextField();
        AddDateDayjLabel = new javax.swing.JLabel();
        AddDateYearjLabel = new javax.swing.JLabel();
        AddDateYearjTextField = new javax.swing.JTextField();
        AddDateStatusjTextField = new javax.swing.JTextField();
        AddDatejButton = new javax.swing.JButton();
        BookingjPanel = new javax.swing.JPanel();
        FlightjComboBox = new javax.swing.JComboBox<>();
        DatejComboBox = new javax.swing.JComboBox<>();
        CustomerjComboBox = new javax.swing.JComboBox<>();
        BookFlightjButton = new javax.swing.JButton();
        BookingStatusjTextField = new javax.swing.JTextField();
        FlightjLabel = new javax.swing.JLabel();
        CustomerLabel = new javax.swing.JLabel();
        DatejLabel = new javax.swing.JLabel();
        CancelFlightCustomerjComboBox = new javax.swing.JComboBox<>();
        CancelFlightDatejComboBox = new javax.swing.JComboBox<>();
        BookFlightjLabel = new javax.swing.JLabel();
        CancelFlightjLabel = new javax.swing.JLabel();
        CancelFlightCustomerjLabel = new javax.swing.JLabel();
        CancelFlightDatejLabel = new javax.swing.JLabel();
        CancelFlightjButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        CancelStatusjTextArea = new javax.swing.JTextArea();
        FlightStatusjPanel = new javax.swing.JPanel();
        FlightStatusFlightjComboBox = new javax.swing.JComboBox<>();
        FlightStatusDatejComboBox = new javax.swing.JComboBox<>();
        FlightStatusjButton = new javax.swing.JButton();
        FlightStatusFlightjLabel = new javax.swing.JLabel();
        FlightStatusDatejLabel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        FlightStatusjTextArea = new javax.swing.JTextArea();
        WaitlistStatusjPanel = new javax.swing.JPanel();
        WaitlistStatusDatejComboBox = new javax.swing.JComboBox<>();
        WaitlistStatusjButton = new javax.swing.JButton();
        WaitlistStatusDatejLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        WaitlistStatusjTextArea = new javax.swing.JTextArea();
        CustomerStatusjPanel = new javax.swing.JPanel();
        CustomerStatusjComboBox = new javax.swing.JComboBox<>();
        CustomerStatusBookingsjTextArea = new javax.swing.JTextArea();
        CustomerjLabel = new javax.swing.JLabel();
        CustomerStatusjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CustomerStatusWaitlistingsjTextArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        DropFlightjComboBox = new javax.swing.JComboBox<>();
        DropFlightjLabel = new javax.swing.JLabel();
        DropFlightjButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        DropFlightjTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        CompanyNamejLabel.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        CompanyNamejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CompanyNamejLabel.setText("Flight-By-Night Airline");
        CompanyNamejLabel.setAlignmentY(0.0F);

        TitlejLabel.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        TitlejLabel.setForeground(new java.awt.Color(255, 51, 51));
        TitlejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitlejLabel.setText("Flight Scheduler");
        TitlejLabel.setAlignmentY(0.0F);

        SignaturejLabel.setFont(new java.awt.Font("Lucida Grande", 0, 8)); // NOI18N
        SignaturejLabel.setText("Mauricio I. Litvak");

        DropFlightjTabbedPane.setBackground(new java.awt.Color(240, 240, 240));

        CustomerNamejLabel.setText("Customer Name:");

        CustomerNamejTextField.setColumns(20);
        CustomerNamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerNamejTextFieldActionPerformed(evt);
            }
        });

        AddCustomerjButton.setText("Add Customer");
        AddCustomerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCustomerjButtonActionPerformed(evt);
            }
        });

        AddCustomerjTextField.setEditable(false);
        AddCustomerjTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AddCustomerjTextField.setText("Add Customer Status Indicator");
        AddCustomerjTextField.setToolTipText("Displays if Customer was added to database succesfully");
        AddCustomerjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCustomerjTextFieldActionPerformed(evt);
            }
        });

        AddFlightNamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFlightNamejTextFieldActionPerformed(evt);
            }
        });

        AddFlightNamejLabel.setText("Flight Name:");

        AddFlightSeatsjLabel.setText("# of Seats:");

        AddFlightjButton.setText("Add Flight");
        AddFlightjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFlightjButtonActionPerformed(evt);
            }
        });

        AddFlightStatusjTextField.setEditable(false);
        AddFlightStatusjTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AddFlightStatusjTextField.setText("Add Flight Status Indicator");

        AddDateMonthjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDateMonthjTextFieldActionPerformed(evt);
            }
        });

        AddCustomerjLabel.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        AddCustomerjLabel.setText("Add Customer");

        AddFlightjLabel.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        AddFlightjLabel.setText("Flight");

        AddDatejLabel.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        AddDatejLabel.setText("Date (yyyy-mm-dd)");

        AddDateMonthjLabel.setText("Month:");

        AddDateDayjLabel.setText("Day:");

        AddDateYearjLabel.setText("Year:");

        AddDateYearjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDateYearjTextFieldActionPerformed(evt);
            }
        });

        AddDateStatusjTextField.setEditable(false);
        AddDateStatusjTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AddDateStatusjTextField.setText("Add Date Status Indicator");

        AddDatejButton.setText("Add Date");
        AddDatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDatejButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ManagejPanelLayout = new javax.swing.GroupLayout(ManagejPanel);
        ManagejPanel.setLayout(ManagejPanelLayout);
        ManagejPanelLayout.setHorizontalGroup(
            ManagejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManagejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ManagejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManagejPanelLayout.createSequentialGroup()
                        .addGroup(ManagejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CustomerNamejLabel)
                            .addComponent(AddFlightNamejLabel)
                            .addGroup(ManagejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(AddFlightSeatsjLabel)
                                .addComponent(AddDateYearjLabel)))
                        .addGap(18, 18, 18)
                        .addGroup(ManagejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AddFlightSeatsjTextField)
                            .addComponent(AddFlightNamejTextField)
                            .addComponent(CustomerNamejTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(ManagejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManagejPanelLayout.createSequentialGroup()
                                .addGroup(ManagejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AddCustomerjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AddFlightjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(ManagejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AddCustomerjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                                    .addComponent(AddFlightStatusjTextField))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManagejPanelLayout.createSequentialGroup()
                                .addComponent(AddFlightjLabel)
                                .addGap(416, 416, 416))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManagejPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(ManagejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ManagejPanelLayout.createSequentialGroup()
                                .addComponent(AddDateYearjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(AddDateMonthjLabel)
                                .addGap(18, 18, 18)
                                .addComponent(AddDateMonthjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(AddDateDayjLabel))
                            .addGroup(ManagejPanelLayout.createSequentialGroup()
                                .addComponent(AddDateStatusjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddDatejButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddDateDayjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
            .addGroup(ManagejPanelLayout.createSequentialGroup()
                .addGap(378, 378, 378)
                .addComponent(AddDatejLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManagejPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddCustomerjLabel)
                .addGap(379, 379, 379))
        );
        ManagejPanelLayout.setVerticalGroup(
            ManagejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManagejPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(AddCustomerjLabel)
                .addGap(18, 18, 18)
                .addGroup(ManagejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerNamejLabel)
                    .addComponent(CustomerNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddCustomerjButton)
                    .addComponent(AddCustomerjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ManagejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManagejPanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(ManagejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddFlightNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddFlightNamejLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ManagejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddFlightSeatsjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddFlightSeatsjLabel)))
                    .addGroup(ManagejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(ManagejPanelLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(AddFlightStatusjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ManagejPanelLayout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(AddFlightjLabel)
                            .addGap(31, 31, 31)
                            .addComponent(AddFlightjButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(ManagejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManagejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AddDateDayjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AddDateDayjLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManagejPanelLayout.createSequentialGroup()
                        .addComponent(AddDatejLabel)
                        .addGap(18, 18, 18)
                        .addGroup(ManagejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddDateMonthjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddDateMonthjLabel)
                            .addComponent(AddDateYearjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddDateYearjLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(ManagejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddDateStatusjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddDatejButton))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        DropFlightjTabbedPane.addTab("Manage", ManagejPanel);

        FlightjComboBox.setModel(new DefaultComboBoxModel(flightList.toArray()));
        FlightjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightjComboBoxActionPerformed(evt);
            }
        });

        DatejComboBox.setModel(new DefaultComboBoxModel(dateList.toArray()));
        DatejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatejComboBoxActionPerformed(evt);
            }
        });

        CustomerjComboBox.setModel(new DefaultComboBoxModel(customerList.toArray()));
        CustomerjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerjComboBoxActionPerformed(evt);
            }
        });

        BookFlightjButton.setText("Book Flight");
        BookFlightjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookFlightjButtonActionPerformed(evt);
            }
        });

        BookingStatusjTextField.setEditable(false);
        BookingStatusjTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BookingStatusjTextField.setText("Booking Status");

        FlightjLabel.setText("Flight:");

        CustomerLabel.setText("Customer: ");

        DatejLabel.setText("Date:");

        CancelFlightCustomerjComboBox.setModel(new DefaultComboBoxModel(customerList.toArray()));

        CancelFlightDatejComboBox.setModel(new DefaultComboBoxModel(dateList.toArray()));

        BookFlightjLabel.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        BookFlightjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BookFlightjLabel.setText("Book Flight");

        CancelFlightjLabel.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        CancelFlightjLabel.setText("Cancel Flight");

        CancelFlightCustomerjLabel.setText("Customer:");

        CancelFlightDatejLabel.setText("Date:");

        CancelFlightjButton.setText("Cancel Flight");

        CancelStatusjTextArea.setColumns(20);
        CancelStatusjTextArea.setRows(5);
        CancelStatusjTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cancel Flight Status", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        jScrollPane2.setViewportView(CancelStatusjTextArea);

        javax.swing.GroupLayout BookingjPanelLayout = new javax.swing.GroupLayout(BookingjPanel);
        BookingjPanel.setLayout(BookingjPanelLayout);
        BookingjPanelLayout.setHorizontalGroup(
            BookingjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingjPanelLayout.createSequentialGroup()
                .addGroup(BookingjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookingjPanelLayout.createSequentialGroup()
                        .addGroup(BookingjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BookingjPanelLayout.createSequentialGroup()
                                .addGap(333, 333, 333)
                                .addComponent(BookFlightjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BookingjPanelLayout.createSequentialGroup()
                                .addGap(362, 362, 362)
                                .addComponent(CancelFlightjLabel))
                            .addGroup(BookingjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(BookingStatusjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(BookingjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(BookingjPanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(FlightjLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(FlightjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)
                                        .addComponent(CustomerLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CustomerjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(DatejLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DatejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BookFlightjButton))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BookingjPanelLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(CancelFlightCustomerjLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CancelFlightCustomerjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CancelFlightDatejLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CancelFlightDatejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(86, 86, 86)
                                        .addComponent(CancelFlightjButton)))))
                        .addGap(0, 155, Short.MAX_VALUE))
                    .addGroup(BookingjPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        BookingjPanelLayout.setVerticalGroup(
            BookingjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingjPanelLayout.createSequentialGroup()
                .addComponent(BookFlightjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BookingjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FlightjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustomerjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DatejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FlightjLabel)
                    .addComponent(CustomerLabel)
                    .addComponent(DatejLabel)
                    .addComponent(BookFlightjButton))
                .addGap(18, 18, 18)
                .addComponent(BookingStatusjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(CancelFlightjLabel)
                .addGap(18, 19, Short.MAX_VALUE)
                .addGroup(BookingjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelFlightCustomerjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelFlightDatejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelFlightCustomerjLabel)
                    .addComponent(CancelFlightDatejLabel)
                    .addComponent(CancelFlightjButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        DropFlightjTabbedPane.addTab("Booking", BookingjPanel);

        FlightStatusFlightjComboBox.setModel(new DefaultComboBoxModel(flightList.toArray()));
        FlightStatusFlightjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightStatusFlightjComboBoxActionPerformed(evt);
            }
        });

        FlightStatusDatejComboBox.setModel(new DefaultComboBoxModel(dateList.toArray()));
        FlightStatusDatejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightStatusDatejComboBoxActionPerformed(evt);
            }
        });

        FlightStatusjButton.setText("Check Status");
        FlightStatusjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightStatusjButtonActionPerformed(evt);
            }
        });

        FlightStatusFlightjLabel.setText("Flight:");

        FlightStatusDatejLabel.setText("Date:");

        FlightStatusjTextArea.setEditable(false);
        FlightStatusjTextArea.setColumns(20);
        FlightStatusjTextArea.setRows(5);
        FlightStatusjTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Flight Status", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        jScrollPane5.setViewportView(FlightStatusjTextArea);

        javax.swing.GroupLayout FlightStatusjPanelLayout = new javax.swing.GroupLayout(FlightStatusjPanel);
        FlightStatusjPanel.setLayout(FlightStatusjPanelLayout);
        FlightStatusjPanelLayout.setHorizontalGroup(
            FlightStatusjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FlightStatusjPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(FlightStatusFlightjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FlightStatusFlightjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addComponent(FlightStatusDatejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FlightStatusDatejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(FlightStatusjButton)
                .addContainerGap(119, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FlightStatusjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        FlightStatusjPanelLayout.setVerticalGroup(
            FlightStatusjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FlightStatusjPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(FlightStatusjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FlightStatusFlightjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FlightStatusDatejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FlightStatusDatejLabel)
                    .addComponent(FlightStatusFlightjLabel)
                    .addComponent(FlightStatusjButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addContainerGap())
        );

        DropFlightjTabbedPane.addTab("Flight Status", FlightStatusjPanel);

        WaitlistStatusDatejComboBox.setModel(new DefaultComboBoxModel(dateList.toArray()));
        WaitlistStatusDatejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WaitlistStatusDatejComboBoxActionPerformed(evt);
            }
        });

        WaitlistStatusjButton.setText("Check Waitlist");
        WaitlistStatusjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WaitlistStatusjButtonActionPerformed(evt);
            }
        });

        WaitlistStatusDatejLabel.setText("Date:");

        WaitlistStatusjTextArea.setEditable(false);
        WaitlistStatusjTextArea.setColumns(20);
        WaitlistStatusjTextArea.setRows(5);
        WaitlistStatusjTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Waitlist Status", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        jScrollPane4.setViewportView(WaitlistStatusjTextArea);

        javax.swing.GroupLayout WaitlistStatusjPanelLayout = new javax.swing.GroupLayout(WaitlistStatusjPanel);
        WaitlistStatusjPanel.setLayout(WaitlistStatusjPanelLayout);
        WaitlistStatusjPanelLayout.setHorizontalGroup(
            WaitlistStatusjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WaitlistStatusjPanelLayout.createSequentialGroup()
                .addGroup(WaitlistStatusjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WaitlistStatusjPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4))
                    .addGroup(WaitlistStatusjPanelLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(WaitlistStatusDatejLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WaitlistStatusDatejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)
                        .addComponent(WaitlistStatusjButton)
                        .addGap(0, 311, Short.MAX_VALUE)))
                .addContainerGap())
        );
        WaitlistStatusjPanelLayout.setVerticalGroup(
            WaitlistStatusjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WaitlistStatusjPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(WaitlistStatusjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WaitlistStatusDatejLabel)
                    .addComponent(WaitlistStatusjButton)
                    .addComponent(WaitlistStatusDatejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                .addContainerGap())
        );

        DropFlightjTabbedPane.addTab("Waitlist Status", WaitlistStatusjPanel);

        CustomerStatusjComboBox.setModel(new DefaultComboBoxModel(customerList.toArray()));
        CustomerStatusjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerStatusjComboBoxActionPerformed(evt);
            }
        });

        CustomerStatusBookingsjTextArea.setEditable(false);
        CustomerStatusBookingsjTextArea.setColumns(20);
        CustomerStatusBookingsjTextArea.setRows(5);
        CustomerStatusBookingsjTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Booking(s):", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        CustomerjLabel.setText("Customer:");

        CustomerStatusjButton.setText("Get Customer Status");
        CustomerStatusjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerStatusjButtonActionPerformed(evt);
            }
        });

        CustomerStatusWaitlistingsjTextArea.setEditable(false);
        CustomerStatusWaitlistingsjTextArea.setColumns(20);
        CustomerStatusWaitlistingsjTextArea.setRows(5);
        CustomerStatusWaitlistingsjTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Waitlisting(s):", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        CustomerStatusWaitlistingsjTextArea.setSize(new java.awt.Dimension(465, 465));
        jScrollPane1.setViewportView(CustomerStatusWaitlistingsjTextArea);

        javax.swing.GroupLayout CustomerStatusjPanelLayout = new javax.swing.GroupLayout(CustomerStatusjPanel);
        CustomerStatusjPanel.setLayout(CustomerStatusjPanelLayout);
        CustomerStatusjPanelLayout.setHorizontalGroup(
            CustomerStatusjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerStatusjPanelLayout.createSequentialGroup()
                .addGroup(CustomerStatusjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CustomerStatusjPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CustomerStatusBookingsjTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1))
                    .addGroup(CustomerStatusjPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(CustomerjLabel)
                        .addGap(34, 34, 34)
                        .addComponent(CustomerStatusjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(CustomerStatusjButton)
                        .addGap(0, 172, Short.MAX_VALUE)))
                .addContainerGap())
        );
        CustomerStatusjPanelLayout.setVerticalGroup(
            CustomerStatusjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerStatusjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CustomerStatusjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerStatusjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustomerjLabel)
                    .addComponent(CustomerStatusjButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustomerStatusjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(CustomerStatusBookingsjTextArea))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        DropFlightjTabbedPane.addTab("Customer Status", CustomerStatusjPanel);

        DropFlightjComboBox.setModel(new DefaultComboBoxModel(flightList.toArray()));

        DropFlightjLabel.setText("Flight:");

        DropFlightjButton.setText("Drop Flight");
        DropFlightjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropFlightjButtonActionPerformed(evt);
            }
        });

        DropFlightjTextArea.setEditable(false);
        DropFlightjTextArea.setColumns(20);
        DropFlightjTextArea.setRows(5);
        DropFlightjTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Drop Flight Status", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        jScrollPane3.setViewportView(DropFlightjTextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(DropFlightjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DropFlightjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(DropFlightjButton)
                .addContainerGap(539, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DropFlightjLabel)
                    .addComponent(DropFlightjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DropFlightjButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addContainerGap())
        );

        DropFlightjTabbedPane.addTab("Drop Flight", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CompanyNamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(320, 320, 320)
                .addComponent(SignaturejLabel))
            .addComponent(DropFlightjTabbedPane)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TitlejLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SignaturejLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CompanyNamejLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TitlejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DropFlightjTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BookFlightjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookFlightjButtonActionPerformed

       String CUSTOMER = (String) CustomerjComboBox.getSelectedItem();
       String FLIGHT = (String) FlightjComboBox.getSelectedItem();
       Date DATE = Date.valueOf(DatejComboBox.getSelectedItem().toString()); 
       booking.addBooking(CUSTOMER, FLIGHT, DATE);
       String customerBooked = CUSTOMER + " is booked for flight " + FLIGHT + " on " + DATE;
       String customerWaitlisted = "'"+ CUSTOMER + "'" + " is waitlisted for flight " + FLIGHT + " on " + DATE;
       if (booking.getBookingStatus())
       {
           BookingStatusjTextField.setText(customerBooked);
       }
       else if (booking.getWaitlistStatus())
       {
           BookingStatusjTextField.setText(customerWaitlisted);
       }
    }//GEN-LAST:event_BookFlightjButtonActionPerformed

    private void CustomerjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerjComboBoxActionPerformed
    String CUSTOMER = (String) CustomerjComboBox.getSelectedItem();
    System.out.println(CUSTOMER);
    }//GEN-LAST:event_CustomerjComboBoxActionPerformed

    private void DatejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatejComboBoxActionPerformed
    String DATE = (String) DatejComboBox.getSelectedItem();
    System.out.println(DATE);
    }//GEN-LAST:event_DatejComboBoxActionPerformed

    private void FlightjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightjComboBoxActionPerformed
    String FLIGHT = (String) FlightjComboBox.getSelectedItem();
    System.out.println(FLIGHT);
    }//GEN-LAST:event_FlightjComboBoxActionPerformed

    private void AddCustomerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCustomerjButtonActionPerformed
        customer.addCustomer(CustomerNamejTextField.getText());
        String added = "'" + CustomerNamejTextField.getText() + "'" + " was added to the Database";
        if (customer.getCustomerAddStatus())
        {
            AddCustomerjTextField.setText(added);
            CustomerjComboBox.addItem(CustomerNamejTextField.getText());
            CancelFlightCustomerjComboBox.addItem(CustomerNamejTextField.getText());
            CustomerStatusjComboBox.addItem(CustomerNamejTextField.getText());
        }
        else
        {
            AddCustomerjTextField.setText("Customer NOT added to Database");
        }
    }//GEN-LAST:event_AddCustomerjButtonActionPerformed

    private void CustomerNamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerNamejTextFieldActionPerformed
        CustomerNamejTextField.getText();
    }//GEN-LAST:event_CustomerNamejTextFieldActionPerformed

    private void FlightStatusFlightjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightStatusFlightjComboBoxActionPerformed
    String FLIGHT = (String) FlightStatusFlightjComboBox.getSelectedItem();
    System.out.println(FLIGHT);
    }//GEN-LAST:event_FlightStatusFlightjComboBoxActionPerformed

    private void FlightStatusDatejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightStatusDatejComboBoxActionPerformed
    Date DATE = Date.valueOf(FlightStatusDatejComboBox.getSelectedItem().toString()); 
    System.out.println(DATE);
    }//GEN-LAST:event_FlightStatusDatejComboBoxActionPerformed

    private void WaitlistStatusDatejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WaitlistStatusDatejComboBoxActionPerformed
    Date DATE = Date.valueOf(WaitlistStatusDatejComboBox.getSelectedItem().toString()); 
    System.out.print(DATE);
    }//GEN-LAST:event_WaitlistStatusDatejComboBoxActionPerformed

    private void FlightStatusjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightStatusjButtonActionPerformed
    //BookingQueries booking = new BookingQueries();
    String FLIGHT = (String) FlightStatusFlightjComboBox.getSelectedItem();
    Date DATE = Date.valueOf(FlightStatusDatejComboBox.getSelectedItem().toString()); 
    //booking.getStatusByFlightDay(FLIGHT, DATE);
    System.out.print(booking.getStatusByFlightDay(FLIGHT, DATE));
    String bookingStatusList = String.join("', '", booking.getStatusByFlightDay(FLIGHT, DATE));
    //String bookingStatus = "Customer(s); " + bookingStatusList + " are booked for " + FLIGHT + " on " + DATE;
    String BookingStatus = "Flight: " + "'" + FLIGHT + "'\n" + "Date: " + "'" + DATE + "'\n\n" + "Customer(s) Booked:\n"; 
    FlightStatusjTextArea.setText(BookingStatus);
    FlightStatusjTextArea.append("'" + bookingStatusList + "' ");
    //for (int i = 0; i < booking.getStatusByFlightDay(FLIGHT, DATE).size(); i ++)
    //    FlightStatusjTextArea.append("'" + booking.getStatusByFlightDay(FLIGHT, DATE).get(i) + "', ");
    }//GEN-LAST:event_FlightStatusjButtonActionPerformed

    private void WaitlistStatusjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WaitlistStatusjButtonActionPerformed
    Waitlist waitlist = new Waitlist();
    Date DATE = Date.valueOf(WaitlistStatusDatejComboBox.getSelectedItem().toString()); 
    //waitlist.getStatusByDay(DATE);
    String waitlistStatusList = String.join(", ", waitlist.getStatusByDay(DATE));
    WaitlistStatusjTextArea.setText("Date: '" + DATE + "'\n\nFlight(s):     Customer(s):\n");
    for (int i = 0; i < waitlist.getStatusByDay(DATE).size(); i = i + 2)
        WaitlistStatusjTextArea.append(waitlist.getStatusByDay(DATE).get(i + 1) + "         " + waitlist.getStatusByDay(DATE).get(i) + "\n");
    }//GEN-LAST:event_WaitlistStatusjButtonActionPerformed

    private void AddCustomerjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCustomerjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddCustomerjTextFieldActionPerformed

    private void AddFlightNamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFlightNamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddFlightNamejTextFieldActionPerformed

    private void AddDateMonthjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDateMonthjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddDateMonthjTextFieldActionPerformed

    private void AddFlightjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFlightjButtonActionPerformed
        String FLIGHT = (String) AddFlightNamejTextField.getText();
        int SEATS = Integer.parseInt(AddFlightSeatsjTextField.getText());
        flight.addFlight(FLIGHT, SEATS);
        String added = "Flight: " + "'" + AddFlightNamejTextField.getText() + "' " + "With: " + "'" + AddFlightSeatsjTextField.getText() +"' " + "seat(s) " + "was added to the Database";
        if (flight.getFlightAddStatus())
        {
            AddFlightStatusjTextField.setText(added);
            FlightjComboBox.addItem(AddFlightNamejTextField.getText());
            FlightStatusFlightjComboBox.addItem(AddFlightNamejTextField.getText());
            DropFlightjComboBox.addItem(AddFlightNamejTextField.getText());
        }
        else
        {
            AddFlightStatusjTextField.setText("Flight NOT added to the Database");
        }
    }//GEN-LAST:event_AddFlightjButtonActionPerformed

    private void AddDatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDatejButtonActionPerformed
        String YEAR = AddDateYearjTextField.getText();
        String MONTH = AddDateMonthjTextField.getText();
        String DAY = AddDateDayjTextField.getText();
        String DATE = YEAR + "-" + MONTH + "-" + DAY;
        Date date= Date.valueOf(DATE);
        day.addDay(date);
        
        String added = "Date: " + "'" + DATE + "' " + "added to the Databse";
        if (day.getDayAddStatus())
        {
            AddDateStatusjTextField.setText(added);
            DatejComboBox.addItem(DATE);
            CancelFlightDatejComboBox.addItem(DATE);
            FlightStatusDatejComboBox.addItem(DATE);
            WaitlistStatusDatejComboBox.addItem(DATE);
        }
        else
        {
            AddDateStatusjTextField.setText("Date NOT added to the Database");
        }
    }//GEN-LAST:event_AddDatejButtonActionPerformed

    private void AddDateYearjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDateYearjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddDateYearjTextFieldActionPerformed

    private void CustomerStatusjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerStatusjButtonActionPerformed
    String CUSTOMER = CustomerStatusjComboBox.getSelectedItem().toString();
    CustomerStatusBookingsjTextArea.setText("Flight    Date\n\n");
    
        for (int i = 0; i < booking.getBookingStatusByCustomer(CUSTOMER).size(); i = i + 2)
        {
            CustomerStatusBookingsjTextArea.append(booking.getBookingStatusByCustomer(CUSTOMER).get(i) + "    " + booking.getBookingStatusByCustomer(CUSTOMER).get(i+1) + "\n");
        }
    if (booking.getBookingStatusByCustomer(CUSTOMER).size() == 0)// status checking to c if it was updated
    {
        CustomerStatusBookingsjTextArea.setText("Customer NOT booked on any Flights");
    }
    
    CustomerStatusWaitlistingsjTextArea.setText("Flight    Date\n\n");
    
        for (int i = 0; i < booking.getWaitlistStatusByCustomer(CUSTOMER).size(); i = i + 2)
        {
            CustomerStatusWaitlistingsjTextArea.append(booking.getWaitlistStatusByCustomer(CUSTOMER).get(i) + "   " + booking.getWaitlistStatusByCustomer(CUSTOMER).get(i + 1) + "\n");
        }
    if (booking.getWaitlistStatusByCustomer(CUSTOMER).size() == 0)//status checking to c if it was update
    {
        CustomerStatusWaitlistingsjTextArea.setText("Customer NOT waitlisted on any Flights");
    }
    }//GEN-LAST:event_CustomerStatusjButtonActionPerformed

    private void CustomerStatusjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerStatusjComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerStatusjComboBoxActionPerformed

    private void DropFlightjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropFlightjButtonActionPerformed
    String FLIGHT = DropFlightjComboBox.getSelectedItem().toString();
    flight.dropFlight(FLIGHT);
    DropFlightjTextArea.setText("");
    if (flight.getFlightDropStatus())
    {
        DropFlightjTextArea.append("Flight:" + " '"+ FLIGHT +  "' " + "was successfully dropped.");
    }
    else
    {
        DropFlightjTextArea.append("Flight:" + " '" + FLIGHT + "' " +"was NOT successfully dropped.");
    }    
    }//GEN-LAST:event_DropFlightjButtonActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCustomerjButton;
    private javax.swing.JLabel AddCustomerjLabel;
    private javax.swing.JTextField AddCustomerjTextField;
    private javax.swing.JLabel AddDateDayjLabel;
    private javax.swing.JTextField AddDateDayjTextField;
    private javax.swing.JLabel AddDateMonthjLabel;
    private javax.swing.JTextField AddDateMonthjTextField;
    private javax.swing.JTextField AddDateStatusjTextField;
    private javax.swing.JLabel AddDateYearjLabel;
    private javax.swing.JTextField AddDateYearjTextField;
    private javax.swing.JButton AddDatejButton;
    private javax.swing.JLabel AddDatejLabel;
    private javax.swing.JLabel AddFlightNamejLabel;
    private javax.swing.JTextField AddFlightNamejTextField;
    private javax.swing.JLabel AddFlightSeatsjLabel;
    private javax.swing.JTextField AddFlightSeatsjTextField;
    private javax.swing.JTextField AddFlightStatusjTextField;
    private javax.swing.JButton AddFlightjButton;
    private javax.swing.JLabel AddFlightjLabel;
    private javax.swing.JButton BookFlightjButton;
    private javax.swing.JLabel BookFlightjLabel;
    private javax.swing.JTextField BookingStatusjTextField;
    private javax.swing.JPanel BookingjPanel;
    private javax.swing.JComboBox<String> CancelFlightCustomerjComboBox;
    private javax.swing.JLabel CancelFlightCustomerjLabel;
    private javax.swing.JComboBox<String> CancelFlightDatejComboBox;
    private javax.swing.JLabel CancelFlightDatejLabel;
    private javax.swing.JButton CancelFlightjButton;
    private javax.swing.JLabel CancelFlightjLabel;
    private javax.swing.JTextArea CancelStatusjTextArea;
    private javax.swing.JLabel CompanyNamejLabel;
    private javax.swing.JLabel CustomerLabel;
    private javax.swing.JLabel CustomerNamejLabel;
    private javax.swing.JTextField CustomerNamejTextField;
    private javax.swing.JTextArea CustomerStatusBookingsjTextArea;
    private javax.swing.JTextArea CustomerStatusWaitlistingsjTextArea;
    private javax.swing.JButton CustomerStatusjButton;
    private javax.swing.JComboBox<String> CustomerStatusjComboBox;
    private javax.swing.JPanel CustomerStatusjPanel;
    private javax.swing.JComboBox<String> CustomerjComboBox;
    private javax.swing.JLabel CustomerjLabel;
    private javax.swing.JComboBox<String> DatejComboBox;
    private javax.swing.JLabel DatejLabel;
    private javax.swing.JButton DropFlightjButton;
    private javax.swing.JComboBox<String> DropFlightjComboBox;
    private javax.swing.JLabel DropFlightjLabel;
    private javax.swing.JTabbedPane DropFlightjTabbedPane;
    private javax.swing.JTextArea DropFlightjTextArea;
    private javax.swing.JComboBox<String> FlightStatusDatejComboBox;
    private javax.swing.JLabel FlightStatusDatejLabel;
    private javax.swing.JComboBox<String> FlightStatusFlightjComboBox;
    private javax.swing.JLabel FlightStatusFlightjLabel;
    private javax.swing.JButton FlightStatusjButton;
    private javax.swing.JPanel FlightStatusjPanel;
    private javax.swing.JTextArea FlightStatusjTextArea;
    private javax.swing.JComboBox<String> FlightjComboBox;
    private javax.swing.JLabel FlightjLabel;
    private javax.swing.JPanel ManagejPanel;
    private javax.swing.JLabel SignaturejLabel;
    private javax.swing.JLabel TitlejLabel;
    private javax.swing.JComboBox<String> WaitlistStatusDatejComboBox;
    private javax.swing.JLabel WaitlistStatusDatejLabel;
    private javax.swing.JButton WaitlistStatusjButton;
    private javax.swing.JPanel WaitlistStatusjPanel;
    private javax.swing.JTextArea WaitlistStatusjTextArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
